#!/usr/bin/env python3
"""Build AKULA's synchronous runtime bathymetry module from a MAREANO GeoTIFF.

The source is a 5.033 m EPSG:25833 WCS subset. The runtime grid is reduced to
321 x 321 samples (25 m spacing across the 8 km chart) so rendering, collision,
sonar occlusion, lidar, and the tactical map all read the same deterministic
terrain without an asynchronous image-loading phase.
"""

from __future__ import annotations

import argparse
import base64
import hashlib
from pathlib import Path

import numpy as np
from PIL import Image


DEFAULT_INPUT = Path("assets/source/mareano-shelf-east/bathymetry05m.tif")
DEFAULT_OUTPUT = Path("src/game/MareanoBathymetry.ts")
RUNTIME_GRID_SIDE = 321
MAP_SIZE_METERS = 8_000
GAME_DEEP_METERS = -310
GAME_SHALLOW_METERS = -145
SOURCE_BBOX = (570_737.629, 7_972_123.956, 578_737.629, 7_980_123.956)
SOURCE_CENTER = (71.873203, 17.152673)
SOURCE_GRID_METERS = 5.033278


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", type=Path, default=DEFAULT_INPUT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    return parser.parse_args()


def chunks(value: str, width: int = 112) -> list[str]:
    return [value[index : index + width] for index in range(0, len(value), width)]


def build_channel_centerline(runtime: np.ndarray) -> np.ndarray:
    """Find a broad, continuous deep-water guide for ecological set dressing."""

    # A 625 m east-west mean ignores isolated pockmarks and trawl cuts. The
    # search stays in the central 5 km so the guide never hugs a chart edge.
    horizontal_kernel = np.ones(25, dtype=np.float64) / 25
    broad = np.stack(
        [np.convolve(row, horizontal_kernel, mode="same") for row in runtime]
    )
    first_column = 60
    last_column = RUNTIME_GRID_SIDE - 60
    raw_columns = (
        np.argmin(broad[:, first_column:last_column], axis=1) + first_column
    )

    # Smooth over roughly one kilometre north-south. This is a placement guide,
    # not an invented terrain feature: the actual grid remains untouched.
    half_window = 20
    padded = np.pad(raw_columns, (half_window, half_window), mode="edge")
    smooth_columns = np.convolve(
        padded,
        np.ones(half_window * 2 + 1, dtype=np.float64) / (half_window * 2 + 1),
        mode="valid",
    )
    center_meters = (
        -MAP_SIZE_METERS / 2
        + smooth_columns / (RUNTIME_GRID_SIDE - 1) * MAP_SIZE_METERS
    )
    return np.rint(center_meters).astype(np.int16)


def main() -> None:
    args = parse_args()
    source_bytes = args.input.read_bytes()
    source = np.asarray(Image.open(args.input), dtype=np.float32)
    valid = np.isfinite(source) & (np.abs(source) < 1e20) & (source != 0)
    if not valid.all():
        invalid_count = int(valid.size - valid.sum())
        raise ValueError(f"Selected WCS subset contains {invalid_count} empty cells")

    runtime_image = Image.fromarray(source).resize(
        (RUNTIME_GRID_SIDE, RUNTIME_GRID_SIDE), Image.Resampling.BOX
    )
    runtime = np.asarray(runtime_image, dtype=np.float32)
    decimeters = np.rint(runtime * 10).astype(np.int16)
    centerline = build_channel_centerline(runtime)
    encoded = base64.b64encode(decimeters.astype("<i2").tobytes()).decode("ascii")

    source_min = float(source.min())
    source_max = float(source.max())
    runtime_min = float(runtime.min())
    runtime_max = float(runtime.max())
    source_hash = hashlib.sha256(source_bytes).hexdigest()
    bbox = ", ".join(f"{value:.3f}" for value in SOURCE_BBOX)
    centerline_values = ", ".join(str(int(value)) for value in centerline)
    encoded_lines = "\n".join(f'  "{part}",' for part in chunks(encoded))

    output = f'''// Generated by scripts/build-mareano-bathymetry.py. Do not hand-edit.

export const MAREANO_BATHYMETRY_METADATA = Object.freeze({{
  title: "MAREANO shelf-east multibeam terrain",
  crs: "EPSG:25833",
  sourceBboxMeters: [{bbox}] as const,
  centerLatitudeLongitude: [{SOURCE_CENTER[0]:.6f}, {SOURCE_CENTER[1]:.6f}] as const,
  sourceGridMeters: {SOURCE_GRID_METERS:.6f},
  runtimeGridSide: {RUNTIME_GRID_SIDE},
  runtimeGridMeters: {MAP_SIZE_METERS / (RUNTIME_GRID_SIDE - 1):.3f},
  sourceDepthRangeMeters: [{source_min:.6f}, {source_max:.6f}] as const,
  runtimeDepthRangeMeters: [{runtime_min:.6f}, {runtime_max:.6f}] as const,
  gameHeightRangeMeters: [{GAME_DEEP_METERS}, {GAME_SHALLOW_METERS}] as const,
  sourceSha256: "{source_hash}",
  license: "CC BY 4.0",
  attribution: "Kartverket / MAREANO",
}});

const MAP_HALF_METERS = {MAP_SIZE_METERS // 2};
const SOURCE_DEPTH_BASE64 = [
{encoded_lines}
].join("");
const SOURCE_DEPTH_DECIMETERS = decodeSignedInt16(SOURCE_DEPTH_BASE64);
const CHANNEL_CENTER_METERS = new Int16Array([{centerline_values}]);

if (
  SOURCE_DEPTH_DECIMETERS.length !==
  MAREANO_BATHYMETRY_METADATA.runtimeGridSide ** 2
) {{
  throw new Error("Invalid generated MAREANO bathymetry payload length");
}}

/** Bilinear sample of the unmodified MAREANO elevation value in metres. */
export function mareanoSourceDepthAt(x: number, z: number): number {{
  const side = MAREANO_BATHYMETRY_METADATA.runtimeGridSide;
  const column = clamp01((x + MAP_HALF_METERS) / (MAP_HALF_METERS * 2)) * (side - 1);
  const row = clamp01((z + MAP_HALF_METERS) / (MAP_HALF_METERS * 2)) * (side - 1);
  const column0 = Math.floor(column);
  const row0 = Math.floor(row);
  const column1 = Math.min(side - 1, column0 + 1);
  const row1 = Math.min(side - 1, row0 + 1);
  const amountX = column - column0;
  const amountZ = row - row0;
  const north = lerp(
    requireSample(SOURCE_DEPTH_DECIMETERS, row0 * side + column0) / 10,
    requireSample(SOURCE_DEPTH_DECIMETERS, row0 * side + column1) / 10,
    amountX,
  );
  const south = lerp(
    requireSample(SOURCE_DEPTH_DECIMETERS, row1 * side + column0) / 10,
    requireSample(SOURCE_DEPTH_DECIMETERS, row1 * side + column1) / 10,
    amountX,
  );
  return lerp(north, south, amountZ);
}}

/**
 * Vertically exaggerate the real 64 m relief into the playable depth window.
 * Horizontal positions and every terrain relationship remain survey-derived.
 */
export function mareanoGameHeightAt(x: number, z: number): number {{
  const sourceDepth = mareanoSourceDepthAt(x, z);
  const [sourceDeep, sourceShallow] =
    MAREANO_BATHYMETRY_METADATA.sourceDepthRangeMeters;
  const [gameDeep, gameShallow] =
    MAREANO_BATHYMETRY_METADATA.gameHeightRangeMeters;
  const amount = clamp01(
    (sourceDepth - sourceDeep) / (sourceShallow - sourceDeep),
  );
  return lerp(gameDeep, gameShallow, amount);
}}

/** Broad survey-derived trough guide used only to place rocks, coral, and QA views. */
export function mareanoChannelCenterAt(z: number): number {{
  const row =
    clamp01((z + MAP_HALF_METERS) / (MAP_HALF_METERS * 2)) *
    (CHANNEL_CENTER_METERS.length - 1);
  const row0 = Math.floor(row);
  const row1 = Math.min(CHANNEL_CENTER_METERS.length - 1, row0 + 1);
  return lerp(
    requireSample(CHANNEL_CENTER_METERS, row0),
    requireSample(CHANNEL_CENTER_METERS, row1),
    row - row0,
  );
}}

function decodeSignedInt16(encoded: string): Int16Array {{
  const binary = atob(encoded);
  const values = new Int16Array(binary.length / 2);
  for (let index = 0; index < values.length; index += 1) {{
    const byteIndex = index * 2;
    values[index] =
      binary.charCodeAt(byteIndex) | (binary.charCodeAt(byteIndex + 1) << 8);
  }}
  return values;
}}

function requireSample(values: Int16Array, index: number): number {{
  const value = values[index];
  if (value === undefined) {{
    throw new Error(`Missing generated MAREANO sample ${{index}}`);
  }}
  return value;
}}

function clamp01(value: number): number {{
  return Math.min(1, Math.max(0, value));
}}

function lerp(start: number, end: number, amount: number): number {{
  return start + (end - start) * amount;
}}
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    print(
        f"Wrote {args.output}: {RUNTIME_GRID_SIDE} x {RUNTIME_GRID_SIDE}, "
        f"source {source_min:.2f}..{source_max:.2f} m, "
        f"runtime {runtime_min:.2f}..{runtime_max:.2f} m"
    )


if __name__ == "__main__":
    main()
